name: firebase_auth_web
description: The web implementation of firebase_auth
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web

version: 5.12.4-a

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  firebase_auth_platform_interface:
#    path: ../firebase_auth_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_auth/firebase_auth_platform_interface
      ref: SwineTech/v5.1.0-a

  firebase_core:
#    path: ../../firebase_core/firebase_core
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: SwineTech/v5.1.0-a

  firebase_core_web:
#    path: ../../firebase_core/firebase_core_web
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_web
      ref: SwineTech/v5.1.0-a

  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.0
  meta: ^1.8.0
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAuthWeb
        fileName: firebase_auth_web.dart
