name: firebase_auth_web
description: The web implementation of firebase_auth
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web
version: 5.3.2

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  firebase_auth_platform_interface:
    path: ../../firebase_auth/firebase_auth_platform_interface
  firebase_core:
    path: ../../firebase_core/firebase_core
  firebase_core_web:
    path: ../../firebase_core/firebase_core_web
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.0
  intl: ^0.17.0
  js: ^0.6.3
  meta: ^1.3.0

dev_dependencies:
  firebase_auth:
    path: ../firebase_auth
  firebase_core_platform_interface:
    path: ../../firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAuthWeb
        fileName: firebase_auth_web.dart
