name: firebase_performance
description:
  Flutter plugin for Google Performance Monitoring for Firebase, an app
  measurement solution that monitors traces and HTTP/S network requests on Android and
  iOS.
homepage: https://firebase.google.com/docs/perf-mon
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_performance/firebase_performance
version: 0.9.4+1-a

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core:
    path: ../../firebase_core/firebase_core
#    git:
#      url: https://github.com/SwineTech-Inc/flutterfire.git
#      path: packages/firebase_core/firebase_core
#      ref: SwineTech/v4.16.1-a

  firebase_core_platform_interface:
    path: ../../firebase_core/firebase_core_platform_interface
#    git:
#      url: https://github.com/SwineTech-Inc/flutterfire.git
#      path: packages/firebase_core/firebase_core_platform_interface
#      ref: SwineTech/v4.16.1-a

  firebase_performance_platform_interface:
    path: ../firebase_performance_platform_interface
#    git:
#      url: https://github.com/SwineTech-Inc/flutterfire.git
#      path: packages/firebase_performance/firebase_performance_platform_interface
#      ref: SwineTech/v4.16.1-a

  firebase_performance_web:
    path: ../firebase_performance_web
#    git:
#      url: https://github.com/SwineTech-Inc/flutterfire.git
#      path: packages/firebase_performance/firebase_performance_web
#      ref: SwineTech/v4.16.1-a

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.0.0
  mockito: ^5.0.0
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.performance
        pluginClass: FlutterFirebasePerformancePlugin
      ios:
        pluginClass: FLTFirebasePerformancePlugin
      web:
        default_package: firebase_performance_web
