name: firebase_performance_platform_interface
description: A common platform interface for the firebase_performance plugin.
version: 0.1.2+1
homepage: https://firebase.flutter.dev/docs/performance/overview

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  _flutterfire_internals:
    path: ../../_flutterfire_internals
  firebase_core:
    path: ../../firebase_core/firebase_core
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface:
    path: ../../firebase_core/firebase_core_platform_interface
  flutter_test:
    sdk: flutter
