name: firebase_performance_platform_interface
description: A common platform interface for the firebase_performance plugin.

version: 0.1.4+38-a
homepage: https://firebase.flutter.dev/docs/performance/overview

publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals:
#    path: ../../_flutterfire_internals
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/_flutterfire_internals
      ref: SwineTech/v5.02-a

  firebase_core:
#    path: ../../firebase_core/firebase_core
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: SwineTech/v5.02-a

  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  firebase_core_platform_interface:
#    path: ../../firebase_core/firebase_core_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: SwineTech/v5.02-a

  flutter_test:
    sdk: flutter
