# FlutterFire_X naming due to package being take already on Pub.dev.
name: firebase_app_installations
description: A Flutter plugin allowing you to use Firebase Installations.

version: 0.3.0+2-a

homepage: https://firebase.google.com/docs/projects/manage-installations#flutter
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_app_installations/firebase_app_installations
topics:
  - firebase
  - installations
  - app
  - identity

publish_to: none

false_secrets:
  - example/**

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_app_installations_platform_interface:
#    path: ../firebase_app_installations_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_app_installations/firebase_app_installations_platform_interface
      ref: SwineTech/v5.02-a

  firebase_app_installations_web:
#    path: ../firebase_app_installations_web
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_app_installations/firebase_app_installations_web
      ref: SwineTech/v5.02-a

  firebase_core:
#    path: ../../firebase_core/firebase_core
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core
      ref: SwineTech/v5.02-a

  firebase_core_platform_interface:
#    path: ../../firebase_core/firebase_core_platform_interface
    git:
      url: https://github.com/SwineTech-Inc/flutterfire.git
      path: packages/firebase_core/firebase_core_platform_interface
      ref: SwineTech/v5.02-a

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  plugin_platform_interface: ^2.1.3

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.installations.firebase_app_installations
        pluginClass: FirebaseInstallationsPlugin
      ios:
        pluginClass: FirebaseInstallationsPlugin
      macos:
        pluginClass: FirebaseInstallationsPlugin
